
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Ixtamer
 */
public class ____Multas_____hacer extends javax.swing.JFrame {
    

   

  
    
    Lista_Multas listaMultas = new Lista_Multas();
   

    public ____Multas_____hacer() {
        initComponents();
        listaMultas.cargarMultasDesdeCarpetas("C:\\Users\\Ixtamer\\Desktop\\archivo proyecto");
       
        
      
        
        
        this.setExtendedState(MAXIMIZED_BOTH);
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Traspasos = new java.awt.Label();
        Descripcion = new javax.swing.JTextField();
        Departamento_txt_ = new javax.swing.JTextField();
        Dpi_tex = new javax.swing.JTextField();
        Fecha_txt__ = new javax.swing.JTextField();
        label1 = new java.awt.Label();
        Placa111 = new java.awt.Label();
        label3 = new java.awt.Label();
        label4 = new java.awt.Label();
        gaurdar_nodo = new javax.swing.JButton();
        Guardar_en_el_txt___ = new javax.swing.JButton();
        label5 = new java.awt.Label();
        monto111 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        __Buscar_Vehiculo___ = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Traspasos.setFont(new java.awt.Font("Perpetua Titling MT", 2, 48)); // NOI18N
        Traspasos.setText("Traspasos");
        jPanel1.add(Traspasos, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 20, 320, 70));

        Descripcion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DescripcionActionPerformed(evt);
            }
        });
        jPanel1.add(Descripcion, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 410, 620, 50));
        jPanel1.add(Departamento_txt_, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 160, 610, 50));
        jPanel1.add(Dpi_tex, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 250, 610, 50));
        jPanel1.add(Fecha_txt__, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 330, 610, 50));

        label1.setFont(new java.awt.Font("Franklin Gothic Heavy", 0, 36)); // NOI18N
        label1.setName(""); // NOI18N
        label1.setText("Monto");
        jPanel1.add(label1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 490, 140, -1));
        label1.getAccessibleContext().setAccessibleName("");

        Placa111.setFont(new java.awt.Font("Franklin Gothic Heavy", 0, 36)); // NOI18N
        Placa111.setName(""); // NOI18N
        Placa111.setText("Departamento");
        jPanel1.add(Placa111, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 160, -1, -1));

        label3.setFont(new java.awt.Font("Franklin Gothic Heavy", 0, 36)); // NOI18N
        label3.setName(""); // NOI18N
        label3.setText("Placa");
        jPanel1.add(label3, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 240, 140, -1));

        label4.setFont(new java.awt.Font("Franklin Gothic Heavy", 0, 36)); // NOI18N
        label4.setName(""); // NOI18N
        label4.setText("Descripcion");
        jPanel1.add(label4, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 420, 220, -1));

        gaurdar_nodo.setText("Realizar");
        gaurdar_nodo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gaurdar_nodoActionPerformed(evt);
            }
        });
        jPanel1.add(gaurdar_nodo, new org.netbeans.lib.awtextra.AbsoluteConstraints(1030, 560, 170, 50));

        Guardar_en_el_txt___.setText("Guardar");
        Guardar_en_el_txt___.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Guardar_en_el_txt___ActionPerformed(evt);
            }
        });
        jPanel1.add(Guardar_en_el_txt___, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 560, 160, 50));

        label5.setFont(new java.awt.Font("Franklin Gothic Heavy", 0, 36)); // NOI18N
        label5.setName(""); // NOI18N
        label5.setText("Fecha");
        jPanel1.add(label5, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 330, 140, -1));
        jPanel1.add(monto111, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 500, 620, 50));

        jButton1.setText("jButton1");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 560, -1, -1));

        __Buscar_Vehiculo___.setText("Buscar");
        __Buscar_Vehiculo___.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                __Buscar_Vehiculo___ActionPerformed(evt);
            }
        });
        jPanel1.add(__Buscar_Vehiculo___, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 30, 120, 50));
        jPanel1.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 36, 240, 40));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1282, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 632, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void gaurdar_nodoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gaurdar_nodoActionPerformed
        try {
    String departamento = Departamento_txt_.getText().trim();
    String placa = Dpi_tex.getText().trim();
    String fecha = Fecha_txt__.getText().trim();
    String descripcion = Descripcion.getText().trim();
    int monto = Integer.parseInt(monto111.getText().trim());

    
     listaMultas.agregarMulta(departamento, placa, fecha, descripcion, monto);
     String ruta = "C:\\Users\\Ixtamer\\Desktop\\archivo proyecto";
    listaMultas.guardarMultasEnArchivosExistentes(ruta);
    
   

    JOptionPane.showMessageDialog(null, "Multa agregada exitosamente.");
} catch (NumberFormatException ex) {
    JOptionPane.showMessageDialog(null, "Monto inválido. Debe ser un número entero.");
}


 

    }//GEN-LAST:event_gaurdar_nodoActionPerformed

    private void Guardar_en_el_txt___ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Guardar_en_el_txt___ActionPerformed
   
       
    }//GEN-LAST:event_Guardar_en_el_txt___ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        Vehiculos atras = new Vehiculos();
        atras.setVisible(true);
        this.dispose();
                          
    }//GEN-LAST:event_jButton1ActionPerformed

    private void __Buscar_Vehiculo___ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event___Buscar_Vehiculo___ActionPerformed
            String placaBuscar =jTextField1.getText().trim();

    long inicio = System.nanoTime();  // Tiempo inicial

    Nodo_Multas resultado = listaMultas.buscarPorPlaca(placaBuscar);

    long fin = System.nanoTime();  // Tiempo final
    double tiempoMs = (fin - inicio) / 1_000_000.0;



    if (resultado != null) {
        JOptionPane.showMessageDialog(null, "Multa encontrada:\n" +
            "Departamento: " + resultado.departamento + "\n" +
            "Fecha: " + resultado.fecha + "\n" +
            "Descripción: " + resultado.Descripcion + "\n" +
            "Monto: " + resultado.monto);
    } else {
        JOptionPane.showMessageDialog(null, "No se encontró multa con esa placa.");
    }

    }//GEN-LAST:event___Buscar_Vehiculo___ActionPerformed

    private void DescripcionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DescripcionActionPerformed
      
    }//GEN-LAST:event_DescripcionActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(____Multas_____hacer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(____Multas_____hacer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(____Multas_____hacer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(____Multas_____hacer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ____Multas_____hacer().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Departamento_txt_;
    private javax.swing.JTextField Descripcion;
    private javax.swing.JTextField Dpi_tex;
    private javax.swing.JTextField Fecha_txt__;
    private javax.swing.JButton Guardar_en_el_txt___;
    private java.awt.Label Placa111;
    private java.awt.Label Traspasos;
    private javax.swing.JButton __Buscar_Vehiculo___;
    private javax.swing.JButton gaurdar_nodo;
    private javax.swing.JButton jButton1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextField1;
    private java.awt.Label label1;
    private java.awt.Label label3;
    private java.awt.Label label4;
    private java.awt.Label label5;
    private javax.swing.JTextField monto111;
    // End of variables declaration//GEN-END:variables
}
