
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;




public class Pantalla extends javax.swing.JFrame {
    
    
   
   

  
  Lista_Multas listaMultas = new Lista_Multas();
    
    
    
    
    
    public Pantalla() {
        
        initComponents();
        
       
        listaMultas.cargarMultasDesdeCarpetas("C:\\Users\\Ixtamer\\Desktop\\archivo proyecto");
        tabla1.setModel(listaMultas.obtenerModeloTabla());
         
         
        
        
        this.setExtendedState(MAXIMIZED_BOTH);
        this.setLocationRelativeTo(null);
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        ImportarMultas = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabla1 = new javax.swing.JTable();
        Placa23 = new javax.swing.JTextField();
        fecha2 = new javax.swing.JTextField();
        Descripcion2 = new javax.swing.JTextField();
        Monto2 = new javax.swing.JTextField();
        Monto = new javax.swing.JLabel();
        placa1 = new javax.swing.JLabel();
        fecha = new javax.swing.JLabel();
        Descripcion = new javax.swing.JLabel();
        Agregar_final = new javax.swing.JButton();
        guarda_documento = new javax.swing.JButton();
        Limpiar = new javax.swing.JButton();
        Buscar = new javax.swing.JButton();
        txtPlacaBuscar = new javax.swing.JTextField();
        Eliminar_elemento = new javax.swing.JButton();
        Modificar = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        depa = new javax.swing.JTextField();
        Modificar___ = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        ImportarMultas.setText("IMPORTAR");
        ImportarMultas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ImportarMultasMouseClicked(evt);
            }
        });
        ImportarMultas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ImportarMultasActionPerformed(evt);
            }
        });
        jPanel1.add(ImportarMultas, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 480, -1, -1));

        jScrollPane1.setPreferredSize(new java.awt.Dimension(452, 400));

        tabla1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Departamento", "Placa", "Fecha", "Descripcion", "Monto"
            }
        ));
        tabla1.getTableHeader().setResizingAllowed(false);
        tabla1.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(tabla1);
        if (tabla1.getColumnModel().getColumnCount() > 0) {
            tabla1.getColumnModel().getColumn(1).setResizable(false);
            tabla1.getColumnModel().getColumn(2).setResizable(false);
            tabla1.getColumnModel().getColumn(3).setResizable(false);
            tabla1.getColumnModel().getColumn(4).setResizable(false);
        }

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 250, 830, 210));
        jPanel1.add(Placa23, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 40, 180, -1));
        jPanel1.add(fecha2, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 80, 180, -1));
        jPanel1.add(Descripcion2, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 120, 180, -1));
        jPanel1.add(Monto2, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 160, 180, -1));

        Monto.setText("Monto");
        jPanel1.add(Monto, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 160, -1, -1));

        placa1.setText("Placa");
        jPanel1.add(placa1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 50, -1, -1));

        fecha.setText("fecha");
        jPanel1.add(fecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 80, -1, -1));

        Descripcion.setText("Descripcion");
        jPanel1.add(Descripcion, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 120, -1, -1));

        Agregar_final.setText("Agregar ");
        Agregar_final.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Agregar_finalMouseClicked(evt);
            }
        });
        Agregar_final.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Agregar_finalActionPerformed(evt);
            }
        });
        jPanel1.add(Agregar_final, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 170, 110, 40));

        guarda_documento.setText("Guardar");
        guarda_documento.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                guarda_documentoMouseClicked(evt);
            }
        });
        jPanel1.add(guarda_documento, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 470, 130, 40));

        Limpiar.setText("Limpiar");
        Limpiar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LimpiarMouseClicked(evt);
            }
        });
        jPanel1.add(Limpiar, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 470, 110, 40));

        Buscar.setText("Buscar");
        Buscar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BuscarMouseClicked(evt);
            }
        });
        Buscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BuscarActionPerformed(evt);
            }
        });
        jPanel1.add(Buscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 40, 100, 40));
        jPanel1.add(txtPlacaBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 46, 200, 30));

        Eliminar_elemento.setText("Eliminar");
        Eliminar_elemento.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Eliminar_elementoMouseClicked(evt);
            }
        });
        jPanel1.add(Eliminar_elemento, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 470, 130, 40));

        Modificar.setText("Eliminar");
        Modificar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ModificarMouseClicked(evt);
            }
        });
        Modificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ModificarActionPerformed(evt);
            }
        });
        jPanel1.add(Modificar, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 170, 110, 40));

        jButton1.setText("prueva ver");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 530, -1, -1));

        jButton2.setText("Atras");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 540, 240, -1));

        jButton3.setText("Traspaso");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 540, 240, -1));

        jButton4.setText("traspaso");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 470, -1, -1));

        jLabel1.setText("Departamento");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 200, -1, -1));
        jPanel1.add(depa, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 200, 190, -1));

        Modificar___.setText("Modificar");
        Modificar___.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Modificar___ActionPerformed(evt);
            }
        });
        jPanel1.add(Modificar___, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 170, 100, -1));
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 100, 150, 40));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 965, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 598, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
   
    private void ImportarMultasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ImportarMultasMouseClicked
       
            
 
    
    }//GEN-LAST:event_ImportarMultasMouseClicked

    private void Agregar_finalMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Agregar_finalMouseClicked
      try {
    String departamento = depa.getText().trim();
    String placa = Placa23.getText().trim();
    String fecha = fecha2.getText().trim();
    String descripcion = Descripcion2.getText().trim();
    int monto = Integer.parseInt(Monto2.getText().trim());

    
     listaMultas.agregarMulta(departamento, placa, fecha, descripcion, monto);
     String ruta = "C:\\Users\\Ixtamer\\Desktop\\archivo proyecto";
    listaMultas.guardarMultasEnArchivosExistentes(ruta);
    
    // Actualiza la tabla después de agregar
    tabla1.setModel(listaMultas.obtenerModeloTabla());
    tabla1.setModel(listaMultas.obtenerModeloTabla());

    JOptionPane.showMessageDialog(null, "Multa agregada exitosamente.");
} catch (NumberFormatException ex) {
    JOptionPane.showMessageDialog(null, "Monto inválido. Debe ser un número entero.");
}

         
         
         
        
       
        
      
    }//GEN-LAST:event_Agregar_finalMouseClicked

    private void guarda_documentoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_guarda_documentoMouseClicked
    
        
        
        
        


    }//GEN-LAST:event_guarda_documentoMouseClicked

    private void LimpiarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LimpiarMouseClicked
        DefaultTableModel modelo = (DefaultTableModel) tabla1.getModel();
        modelo.setRowCount(0);
    }//GEN-LAST:event_LimpiarMouseClicked

    private void BuscarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BuscarMouseClicked
        String placaBuscada = txtPlacaBuscar.getText().trim();

        if (placaBuscada.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Por favor ingresa una placa.");
            return;
        }

        DefaultTableModel modelo = (DefaultTableModel) tabla1.getModel();
        boolean encontrado = false;

        for (int i = 0; i < modelo.getRowCount(); i++) {
            String placaTabla = modelo.getValueAt(i, 0).toString(); 

            if (placaTabla.equalsIgnoreCase(placaBuscada)) {
                tabla1.setRowSelectionInterval(i, i); 
                tabla1.scrollRectToVisible(tabla1.getCellRect(i, 0, true)); 
                encontrado = true;
                break;
            }
        }

        if (!encontrado) {
            JOptionPane.showMessageDialog(null, "Placa no encontrada.");
        }
    }//GEN-LAST:event_BuscarMouseClicked

    private void Eliminar_elementoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Eliminar_elementoMouseClicked
       
    }//GEN-LAST:event_Eliminar_elementoMouseClicked

    private void ModificarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ModificarMouseClicked
     
    
        
        
        
    }//GEN-LAST:event_ModificarMouseClicked

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
       
    }//GEN-LAST:event_jButton1MouseClicked

    private void ImportarMultasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ImportarMultasActionPerformed
     

    }//GEN-LAST:event_ImportarMultasActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
         Pantalla_traspaso secundaria = new Pantalla_traspaso();
         secundaria.setVisible(true);
         this.dispose(); 

    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        Vehiculos atras = new Vehiculos();
        atras.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void Modificar___ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Modificar___ActionPerformed
        String departamento = depa.getText().trim();
        String placa = Placa23.getText().trim();
        String nuevaFecha = fecha2.getText().trim();
        String nuevaDescripcion = Descripcion2.getText().trim();
        int nuevoMonto;

        try {
            nuevoMonto = Integer.parseInt(Monto2.getText().trim());
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(null, "Monto inválido. Ingrese un número.");
            return;
        }

        boolean actualizado = ActualizarMulta.actualizarMulta(listaMultas, departamento, placa, nuevaFecha, nuevaDescripcion, nuevoMonto);

        if (actualizado) {
            JOptionPane.showMessageDialog(null, "Multa actualizada con éxito.");
            // Aquí puedes actualizar también la JTable:
            tabla1.setModel(listaMultas.obtenerModeloTabla());
            listaMultas.guardarMultasEnArchivosExistentes("C:\\Users\\Ixtamer\\Desktop\\archivo proyecto");
        } else {
            JOptionPane.showMessageDialog(null, "Multa no encontrada.");
        }
    }//GEN-LAST:event_Modificar___ActionPerformed

    private void BuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BuscarActionPerformed
       String placaBuscar = txtPlacaBuscar.getText().trim();
        DefaultTableModel modelo = (DefaultTableModel) tabla1.getModel();

        long inicio = System.nanoTime();  // Tiempo inicial
        boolean encontrado = false;

        for (int i = 0; i < modelo.getRowCount(); i++) {
            String placa = modelo.getValueAt(i, 1).toString(); // Columna 1 = Placa
            if (placa.equalsIgnoreCase(placaBuscar)) {
                tabla1.setRowSelectionInterval(i, i);  // Selecciona la fila
                encontrado = true;
                break;
            }
        }

        long fin = System.nanoTime();  // Tiempo final
        double tiempoMs = (fin - inicio) / 1_000_000.0;  // Convertir a milisegundos
        jLabel2.setText(String.format("Tiempo búsqueda: %.3f ms", tiempoMs));

        if (encontrado) {
            JOptionPane.showMessageDialog(null, "Multa encontrada.");
        } else {
            JOptionPane.showMessageDialog(null, "No se encontró multa con esa placa.");
        }

    }//GEN-LAST:event_BuscarActionPerformed

    private void Agregar_finalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Agregar_finalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Agregar_finalActionPerformed

    private void ModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ModificarActionPerformed
        String placaEliminar = txtPlacaBuscar.getText().trim();

        boolean eliminado = listaMultas.eliminarPorPlaca(placaEliminar);
        listaMultas.guardarMultasEnArchivosExistentes("C:\\Users\\Ixtamer\\Desktop\\archivo proyecto");

        if (eliminado) {
            JOptionPane.showMessageDialog(null, "Multa eliminada correctamente.");
            tabla1.setModel(listaMultas.obtenerModeloTabla()); // Refrescar la tabla
        } else {
            JOptionPane.showMessageDialog(null, "No se encontró multa con esa placa.");
        }
    }//GEN-LAST:event_ModificarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Pantalla.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Pantalla.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Pantalla.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Pantalla.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Pantalla().setVisible(true);
            }
        });
    }
    
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Agregar_final;
    private javax.swing.JButton Buscar;
    private javax.swing.JLabel Descripcion;
    private javax.swing.JTextField Descripcion2;
    private javax.swing.JButton Eliminar_elemento;
    private javax.swing.JButton ImportarMultas;
    private javax.swing.JButton Limpiar;
    private javax.swing.JButton Modificar;
    private javax.swing.JButton Modificar___;
    private javax.swing.JLabel Monto;
    private javax.swing.JTextField Monto2;
    private javax.swing.JTextField Placa23;
    private javax.swing.JTextField depa;
    private javax.swing.JLabel fecha;
    private javax.swing.JTextField fecha2;
    private javax.swing.JButton guarda_documento;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel placa1;
    private javax.swing.JTable tabla1;
    private javax.swing.JTextField txtPlacaBuscar;
    // End of variables declaration//GEN-END:variables
}

