
import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;




public class Pantalla extends javax.swing.JFrame {
    
    
    DefaultTableModel modeloVehiculos = new DefaultTableModel();
    DefaultTableModel modeloTraspasos = new DefaultTableModel();
   

  
 
    
    Lista_Doble list = new Lista_Doble();
    Lista_Vehiculos listaVehiculos = new Lista_Vehiculos();
    Lista_Traspasos Tras = new Lista_Traspasos();
    

    File archivo;
    FileReader fr;
    BufferedReader br;
    
    
    
    public Pantalla() {
        
        initComponents();
         Importar_archivos_multas.cargarTodosLosArchivos_multas(modeloVehiculos, list, listaVehiculos);
          Importar_archivos_multas.cargarTraspasos(modeloTraspasos, Tras, listaVehiculos);
         
        
        
        this.setExtendedState(MAXIMIZED_BOTH);
        this.setLocationRelativeTo(null);
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        ImportarMultas = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabla1 = new javax.swing.JTable();
        Placa23 = new javax.swing.JTextField();
        fecha2 = new javax.swing.JTextField();
        Descripcion2 = new javax.swing.JTextField();
        Monto2 = new javax.swing.JTextField();
        Monto = new javax.swing.JLabel();
        placa1 = new javax.swing.JLabel();
        fecha = new javax.swing.JLabel();
        Descripcion = new javax.swing.JLabel();
        Agregar_final = new javax.swing.JButton();
        guarda_documento = new javax.swing.JButton();
        Agreagar_prin = new javax.swing.JButton();
        Limpiar = new javax.swing.JButton();
        Buscar = new javax.swing.JButton();
        txtPlacaBuscar = new javax.swing.JTextField();
        Eliminar_elemento = new javax.swing.JButton();
        Modificar = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        ImportarMultas.setText("IMPORTAR");
        ImportarMultas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ImportarMultasMouseClicked(evt);
            }
        });
        ImportarMultas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ImportarMultasActionPerformed(evt);
            }
        });
        jPanel1.add(ImportarMultas, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 450, -1, -1));

        jScrollPane1.setPreferredSize(new java.awt.Dimension(452, 400));

        tabla1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Departamento", "Placa", "Fecha", "Descripcion", "Monto"
            }
        ));
        tabla1.getTableHeader().setResizingAllowed(false);
        tabla1.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(tabla1);
        if (tabla1.getColumnModel().getColumnCount() > 0) {
            tabla1.getColumnModel().getColumn(1).setResizable(false);
            tabla1.getColumnModel().getColumn(2).setResizable(false);
            tabla1.getColumnModel().getColumn(3).setResizable(false);
            tabla1.getColumnModel().getColumn(4).setResizable(false);
        }

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 220, 830, 210));
        jPanel1.add(Placa23, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 40, 180, -1));
        jPanel1.add(fecha2, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 80, 180, -1));
        jPanel1.add(Descripcion2, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 120, 180, -1));
        jPanel1.add(Monto2, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 160, 180, -1));

        Monto.setText("Monto");
        jPanel1.add(Monto, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 160, -1, -1));

        placa1.setText("Placa");
        jPanel1.add(placa1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 50, -1, -1));

        fecha.setText("fecha");
        jPanel1.add(fecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 80, -1, -1));

        Descripcion.setText("Descripcion");
        jPanel1.add(Descripcion, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 120, -1, -1));

        Agregar_final.setText("Agregar Final");
        Agregar_final.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Agregar_finalMouseClicked(evt);
            }
        });
        jPanel1.add(Agregar_final, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 170, 110, 40));

        guarda_documento.setText("Guardar");
        guarda_documento.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                guarda_documentoMouseClicked(evt);
            }
        });
        jPanel1.add(guarda_documento, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 440, 130, 40));

        Agreagar_prin.setText("Agregar Principio");
        Agreagar_prin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Agreagar_prinMouseClicked(evt);
            }
        });
        jPanel1.add(Agreagar_prin, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 170, 130, 40));

        Limpiar.setText("Limpiar");
        Limpiar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LimpiarMouseClicked(evt);
            }
        });
        jPanel1.add(Limpiar, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 440, 110, 40));

        Buscar.setText("Buscar");
        Buscar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BuscarMouseClicked(evt);
            }
        });
        jPanel1.add(Buscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 40, 100, 40));
        jPanel1.add(txtPlacaBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 46, 200, 30));

        Eliminar_elemento.setText("Eliminar");
        Eliminar_elemento.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Eliminar_elementoMouseClicked(evt);
            }
        });
        jPanel1.add(Eliminar_elemento, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 440, 130, 40));

        Modificar.setText("Modificar");
        Modificar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ModificarMouseClicked(evt);
            }
        });
        jPanel1.add(Modificar, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 170, 110, 40));

        jButton1.setText("prueva ver");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 490, -1, -1));

        jButton2.setText("Atras");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 540, 240, -1));

        jButton3.setText("Traspaso");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 540, 240, -1));

        jButton4.setText("traspaso");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 450, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 965, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 598, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
   
    private void ImportarMultasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ImportarMultasMouseClicked
       
            
 
    
    }//GEN-LAST:event_ImportarMultasMouseClicked

    private void Agregar_finalMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Agregar_finalMouseClicked
        String placa = Placa23.getText();
        String fecha = fecha2.getText();
        String descripcion = Descripcion2.getText();
        int monto = Integer.parseInt(Monto2.getText());
        
        list.insetarfinal(descripcion, placa, fecha, descripcion, monto);
        
         DefaultTableModel modelo = (DefaultTableModel) tabla1.getModel();
         modelo.addRow(new Object[]{placa, fecha, descripcion, monto});
         
          Placa23.setText("");
          
           Placa23.setText("");
           fecha2.setText("");
           Descripcion2.setText("");
           Monto2.setText("");

         
         
         
        
       
        
      
    }//GEN-LAST:event_Agregar_finalMouseClicked

    private void guarda_documentoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_guarda_documentoMouseClicked
     try (BufferedWriter bw = new BufferedWriter(new FileWriter(archivo))) {
        Nodo_Doble aux = list.getCabeza(); 

        while (aux != null) {
           
            String linea = aux.Placa + "," + aux.fecha + "," + aux.Descripcion + "," + aux.monto;
            bw.write(linea); 
            bw.newLine();    
            aux = aux.Siguiente; 
        }

        System.out.println("¡Lista guardada en el archivo correctamente!");
    } catch (IOException e) {
        System.out.println("Error al guardar: " + e.getMessage());
    
}
        
        
        
        
        


    }//GEN-LAST:event_guarda_documentoMouseClicked

    private void Agreagar_prinMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Agreagar_prinMouseClicked
        
    }//GEN-LAST:event_Agreagar_prinMouseClicked

    private void LimpiarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LimpiarMouseClicked
        DefaultTableModel modelo = (DefaultTableModel) tabla1.getModel();
        modelo.setRowCount(0);
    }//GEN-LAST:event_LimpiarMouseClicked

    private void BuscarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BuscarMouseClicked
        String placaBuscada = txtPlacaBuscar.getText().trim();

        if (placaBuscada.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Por favor ingresa una placa.");
            return;
        }

        DefaultTableModel modelo = (DefaultTableModel) tabla1.getModel();
        boolean encontrado = false;

        for (int i = 0; i < modelo.getRowCount(); i++) {
            String placaTabla = modelo.getValueAt(i, 0).toString(); 

            if (placaTabla.equalsIgnoreCase(placaBuscada)) {
                tabla1.setRowSelectionInterval(i, i); 
                tabla1.scrollRectToVisible(tabla1.getCellRect(i, 0, true)); 
                encontrado = true;
                break;
            }
        }

        if (!encontrado) {
            JOptionPane.showMessageDialog(null, "Placa no encontrada.");
        }
    }//GEN-LAST:event_BuscarMouseClicked

    private void Eliminar_elementoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Eliminar_elementoMouseClicked
        int filaSeleccionada = tabla1.getSelectedRow();

        if (filaSeleccionada != -1) {
            String placa = tabla1.getValueAt(filaSeleccionada, 0).toString(); 
            list.eliminarPorPlaca(placa); 
            ((DefaultTableModel) tabla1.getModel()).removeRow(filaSeleccionada); 
            JOptionPane.showMessageDialog(null, "Registro eliminado correctamente.");
        } else {
            JOptionPane.showMessageDialog(null, "Por favor selecciona una fila para eliminar.");
        }
    }//GEN-LAST:event_Eliminar_elementoMouseClicked

    private void ModificarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ModificarMouseClicked
        int fila_seleccionada = tabla1.getSelectedRow();

            if (fila_seleccionada == -1) {
                JOptionPane.showMessageDialog(null, "Selecciona una fila para modificar.");
                return;
            }

            String Nuevaplaca = Placa23.getText().trim();
            String NuevaFecha = fecha2.getText().trim();
            String NuevaDescripcion = Descripcion2.getText().trim();
            String NuevoMonto = Monto2.getText().trim();

            if (Nuevaplaca.isEmpty() || NuevaFecha.isEmpty() || NuevaDescripcion.isEmpty() || NuevoMonto.isEmpty()) {
                JOptionPane.showMessageDialog(null, "Por favor llena todos los campos antes de modificar.");
                return;
            }

            int nuevoMonto;
            try {
                nuevoMonto = Integer.parseInt(NuevoMonto);
            } catch (NumberFormatException e) {
                JOptionPane.showMessageDialog(null, "Monto inválido. Debe ser un número.");
                return;
            }

            String Placatabla = tabla1.getValueAt(fila_seleccionada, 0).toString();
            Nodo_Doble nodo = list.buscarPorPlaca(Placatabla);

            if (nodo != null) {
                nodo.Placa = Nuevaplaca;
                nodo.fecha = NuevaFecha;
                nodo.Descripcion = NuevaDescripcion;
                nodo.monto = nuevoMonto;

                DefaultTableModel modelo = (DefaultTableModel) tabla1.getModel();
                modelo.setValueAt(Nuevaplaca, fila_seleccionada, 0);
                modelo.setValueAt(NuevaFecha, fila_seleccionada, 1);
                modelo.setValueAt(NuevaDescripcion, fila_seleccionada, 2);
                modelo.setValueAt(nuevoMonto, fila_seleccionada, 3);

                JOptionPane.showMessageDialog(null, "Registro modificado correctamente.");
            } else {
                JOptionPane.showMessageDialog(null, "No se encontró el registro a modificar.");
            }



    
        
        
        
    }//GEN-LAST:event_ModificarMouseClicked

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        Nodo_Doble actual = list.cabeza;
            StringBuilder datos = new StringBuilder();

            while (actual != null) {
                datos.append("Placa: ").append(actual.Placa).append("\n");
                datos.append("Fecha: ").append(actual.fecha).append("\n");
                datos.append("Descripción: ").append(actual.Descripcion).append("\n");
                datos.append("Monto: ").append(actual.monto).append("\n");
                datos.append("-------------------------\n");
                actual = actual.Siguiente;
            }

            if (datos.length() == 0) {
                JOptionPane.showMessageDialog(null, "La lista está vacía.");
            } else {
                JOptionPane.showMessageDialog(null, datos.toString());
            }
    }//GEN-LAST:event_jButton1MouseClicked

    private void ImportarMultasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ImportarMultasActionPerformed
         DefaultTableModel modelo = (DefaultTableModel) tabla1.getModel();
        modelo.setRowCount(0);
      
        Importar_archivos_multas.cargarTodosLosArchivos_multas(modelo, list, listaVehiculos);

    }//GEN-LAST:event_ImportarMultasActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
         Pantalla_traspaso secundaria = new Pantalla_traspaso();
         secundaria.setVisible(true);
         this.dispose(); 

    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        Vehiculos atras = new Vehiculos();
        atras.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Pantalla.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Pantalla.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Pantalla.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Pantalla.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Pantalla().setVisible(true);
            }
        });
    }
    
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Agreagar_prin;
    private javax.swing.JButton Agregar_final;
    private javax.swing.JButton Buscar;
    private javax.swing.JLabel Descripcion;
    private javax.swing.JTextField Descripcion2;
    private javax.swing.JButton Eliminar_elemento;
    private javax.swing.JButton ImportarMultas;
    private javax.swing.JButton Limpiar;
    private javax.swing.JButton Modificar;
    private javax.swing.JLabel Monto;
    private javax.swing.JTextField Monto2;
    private javax.swing.JTextField Placa23;
    private javax.swing.JLabel fecha;
    private javax.swing.JTextField fecha2;
    private javax.swing.JButton guarda_documento;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel placa1;
    private javax.swing.JTable tabla1;
    private javax.swing.JTextField txtPlacaBuscar;
    // End of variables declaration//GEN-END:variables
}

