
import java.awt.Desktop;
import java.io.File;
import java.io.FileWriter;
import java.io.IOException;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Ixtamer
 */
public class Vehiculos extends javax.swing.JFrame {
    
    
    

    ArbolVehiculos arbol = new ArbolVehiculos(); 
   
   
    
    
    
    public Vehiculos() {
        initComponents();
        String ruta = "C:\\Users\\Ixtamer\\Desktop\\archivo proyecto";  // <-- cambia esto a tu ruta real
        DefaultTableModel modelo = arbol.cargarVehiculosDesdeCarpetas(ruta);
        tabla_vehi.setModel(modelo);
        
        
      
        
        
        
        
        this.setExtendedState(MAXIMIZED_BOTH);
        this.setLocationRelativeTo(null);
        
    }
    private void mostrarEnTabla(ArrayList<Vehiculo> lista) {
    String[] columnas = {"Departamento", "Placa", "DPI", "Nombre", "Marca", "Modelo", "Año", "Multas", "Traspasos"};
    DefaultTableModel modelo = new DefaultTableModel(columnas, 0);

    for (Vehiculo v : lista) {
        Object[] fila = {
            v.getDepartamento(),
            v.getPlaca(),
            v.getDpi(),
            v.getNombre(),
            v.getMarca(),
            v.getModelo(),
            v.getAno(),
            v.getMultas(),
            v.getTraspasos()
        };
        modelo.addRow(fila);
    }

    tabla_vehi.setModel(modelo);
}
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabla_vehi = new javax.swing.JTable();
        Multa = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        pre = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        post = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        Buscar___ = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tabla_vehi.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Departamento", "Placa", "DPI", "Nombre", "Marca", "Modelo", "Anio", "Multas", "Traspasos"
            }
        ));
        jScrollPane1.setViewportView(tabla_vehi);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, 980, 200));

        Multa.setText("Multas");
        Multa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MultaActionPerformed(evt);
            }
        });
        jPanel1.add(Multa, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 420, 140, -1));

        jButton2.setText("Listado Traspaso");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 330, -1, -1));

        jButton3.setText("Listado Multa");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 330, 140, -1));

        pre.setText("Preorden");
        pre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                preActionPerformed(evt);
            }
        });
        jPanel1.add(pre, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 270, -1, -1));

        jButton4.setText("Ver arbol");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 270, -1, -1));

        post.setText("Post");
        post.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                postActionPerformed(evt);
            }
        });
        jPanel1.add(post, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 270, -1, -1));

        jButton5.setText("In-orden");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 270, -1, -1));

        Buscar___.setText("Buscar");
        Buscar___.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Buscar___ActionPerformed(evt);
            }
        });
        jPanel1.add(Buscar___, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 20, -1, -1));
        jPanel1.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 20, 310, -1));
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 340, 280, 120));

        jButton1.setText("Tabla abl");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 280, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1074, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 513, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void MultaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MultaActionPerformed
         ____Multas_____hacer secundaria = new ____Multas_____hacer();
         secundaria.setVisible(true);
         this.dispose(); 

    }//GEN-LAST:event_MultaActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        Pantalla_traspaso tras = new Pantalla_traspaso();
         tras.setVisible(true);
         this.dispose(); 

    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        Pantalla multas = new Pantalla();
        multas.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void preActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_preActionPerformed
       ArrayList<Vehiculo> lista = arbol.recorridoPreorden();
    mostrarEnTabla(lista);
    }//GEN-LAST:event_preActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
            try {
        // 1. Obtener el código DOT desde tu árbol
        String dot = arbol.generarDOT(); // Asegúrate que "arbolVehiculos" esté accesible

        // 2. Guardar el archivo .dot
        FileWriter writer = new FileWriter("arbol_vehiculos.dot");
        writer.write(dot);
        writer.close();

        // 3. Generar imagen con Graphviz
        ProcessBuilder pb = new ProcessBuilder("dot", "-Tpng", "arbol_vehiculos.dot", "-o", "arbol_vehiculos.png");
        
        
        //dot", "-Tpng", "arbol_vehiculos.dot", "-o", "arbol_vehiculos.png
        
       
        pb.redirectErrorStream(true);
        Process p = pb.start();
        int exitCode = p.waitFor();

        if (exitCode == 0) {
            JOptionPane.showMessageDialog(this, "Imagen generada exitosamente.");

            Desktop.getDesktop().open(new File("arbol_vehiculos.png"));
        } else {
            JOptionPane.showMessageDialog(this, "Error al generar la imagen con Graphviz.");
        }

    } catch (IOException | InterruptedException ex) {
        ex.printStackTrace();
        JOptionPane.showMessageDialog(this, "Error: " + ex.getMessage());
    }

    }//GEN-LAST:event_jButton4ActionPerformed

    private void postActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_postActionPerformed
         ArrayList<Vehiculo> lista = arbol.recorridoPostorden();
        mostrarEnTabla(lista);


    }//GEN-LAST:event_postActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
         ArrayList<Vehiculo> lista = arbol.recorridoInorden();
        mostrarEnTabla(lista);
    }//GEN-LAST:event_jButton5ActionPerformed

    private void Buscar___ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Buscar___ActionPerformed
     String placaBuscada = jTextField1.getText().trim();

    if (placaBuscada.isEmpty()) {
        JOptionPane.showMessageDialog(this, "Ingrese una placa para buscar.");
        return;
    }

    // Buscar en el árbol y medir el tiempo
    long inicio = System.nanoTime();
    Vehiculo vehiculoEncontrado = arbol.buscarVehiculoConTiempo(placaBuscada);
    long fin = System.nanoTime();
    double tiempoMs = (fin - inicio) / 1_000_000.0;

    // Mostrar tiempo de búsqueda
    jLabel1.setText("Tiempo de búsqueda: " + tiempoMs + " ms");

    if (vehiculoEncontrado != null) {
        // Buscar en la tabla y seleccionar la fila
        DefaultTableModel modelo = (DefaultTableModel) tabla_vehi.getModel();
        for (int i = 0; i < modelo.getRowCount(); i++) {
            String placaEnTabla = modelo.getValueAt(i, 1).toString(); // Columna de placa
            if (placaEnTabla.equalsIgnoreCase(placaBuscada)) {
                tabla_vehi.setRowSelectionInterval(i, i);
                tabla_vehi.scrollRectToVisible(tabla_vehi.getCellRect(i, 0, true));
                return;
            }
        }

        // Si no se encontró en la tabla (pero sí en el árbol)
        JOptionPane.showMessageDialog(this, "Vehículo encontrado en el árbol, pero no se muestra en la tabla.");
    } else {
        JOptionPane.showMessageDialog(this, "Vehículo no encontrado.");
    }

    }//GEN-LAST:event_Buscar___ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        Avl_arboles_frame avl = new Avl_arboles_frame();
        avl.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Vehiculos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Vehiculos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Vehiculos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Vehiculos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Vehiculos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Buscar___;
    private javax.swing.JButton Multa;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JButton post;
    private javax.swing.JButton pre;
    private javax.swing.JTable tabla_vehi;
    // End of variables declaration//GEN-END:variables

   
}
