
import javax.swing.table.DefaultTableModel;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Ixtamer
 */
public class Estadistica extends javax.swing.JFrame {

    /**
     * Creates new form Estadistica
     */
    public Estadistica() {
        initComponents();
        ControladorSistema.arbolVehiculos.cargarVehiculosDesdeCarpetas("C:\\Users\\Ixtamer\\Desktop\\archivo proyecto");
       
    }
    private int contarVehiculos(NodoAVL nodo) {
    if (nodo == null) return 0;
    return 1 + contarVehiculos(nodo.izquierdo) + contarVehiculos(nodo.derecho);
}
    private void recorrerAVL(NodoAVL nodo, Vehiculo[] maxMultas, Vehiculo[] maxTraspasos) {
    if (nodo == null) return;

    Vehiculo actual = nodo.vehiculo;

    if (actual != null) {
        if (maxMultas[0] == null || actual.getMultas() > maxMultas[0].getMultas()) {
            maxMultas[0] = actual;
        }

        if (maxTraspasos[0] == null || actual.getTraspasos() > maxTraspasos[0].getTraspasos()) {
            maxTraspasos[0] = actual;
        }
    }

    recorrerAVL(nodo.izquierdo, maxMultas, maxTraspasos);
    recorrerAVL(nodo.derecho, maxMultas, maxTraspasos);
}
    
    private void mostrarEnTabla(javax.swing.JTable tabla, Vehiculo v, String tipo) {
    DefaultTableModel modelo = new DefaultTableModel();
    modelo.addColumn("Placa");
    modelo.addColumn("Nombre");
    modelo.addColumn("DPI");
    modelo.addColumn(tipo);

    if (v != null) {
        modelo.addRow(new Object[]{
            v.getPlaca(), v.getNombre(), v.getDpi(),
            tipo.equals("Multas") ? v.getMultas() : v.getTraspasos()
        });
    }

    tabla.setModel(modelo);
}


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Estadisticas = new javax.swing.JButton();
        lblTotalVehiculos = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Estadisticas.setText("Estadistica");
        Estadisticas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EstadisticasActionPerformed(evt);
            }
        });
        jPanel1.add(Estadisticas, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 200, 210, -1));
        jPanel1.add(lblTotalVehiculos, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 30, 210, 120));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 70, 650, 110));

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTable2);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 230, 650, 130));

        jButton1.setText("Atras");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 470, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void EstadisticasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EstadisticasActionPerformed
       
       
        
        int total = contarVehiculos(ControladorSistema.arbolVehiculos.getRaiz());
    lblTotalVehiculos.setText("Total vehículos: " + total);

    Vehiculo[] maxMultas = new Vehiculo[1];
    Vehiculo[] maxTraspasos = new Vehiculo[1];

    recorrerAVL(ControladorSistema.arbolVehiculos.getRaiz(), maxMultas, maxTraspasos);

    mostrarEnTabla(jTable1, maxTraspasos[0], "Traspasos");
    mostrarEnTabla(jTable2, maxMultas[0], "Multas");lblTotalVehiculos.setText("Total vehículos: " + total);
    
    
    }//GEN-LAST:event_EstadisticasActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        VentanaPrincipal VentanaTraspaso = new VentanaPrincipal(); // pasamos la ventana principal
        VentanaTraspaso.setVisible(true);
        this.setVisible(false); 
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Estadistica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Estadistica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Estadistica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Estadistica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Estadistica().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Estadisticas;
    private javax.swing.JButton jButton1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JLabel lblTotalVehiculos;
    // End of variables declaration//GEN-END:variables
}
