
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Ixtamer
 */
public class VentanaPrincipal extends javax.swing.JFrame {

    
 
    
    
    public VentanaPrincipal() {
        initComponents();
        
       
        
        
        String ruta = "C:\\Users\\Ixtamer\\Desktop\\archivo proyecto";  // ← CAMBIA esto a tu ruta real
        DefaultTableModel modelo = ControladorSistema.arbolVehiculos.cargarVehiculosDesdeCarpetas(ruta);
        DefaultTableModel modelo1 = ControladorSistema.arbolesbb.cargarVehiculosDesdeCarpetas(ruta);
        
 
     
       
        
    
        
        
        
        
    jTable1.setModel(modelo);
    jTable2.setModel(modelo1);
    
    
    
    
        
    }
    
    
    
    
    public void actualizarTablaVehiculos() {
    DefaultTableModel modelo = ControladorSistema.arbolVehiculos.recorrerInOrden();
   
    jTable1.setModel(modelo);
    
    
    
    
}
    
    
    
    
    public void actualizarTablaVehiculosbb() {
    DefaultTableModel modelo1 = ControladorSistema.arbolesbb.recorrerInOrden();
    jTable2.setModel(modelo1);

   
    
    
    
    }
    
    
    
    
    
    
    
    private void descifrarAVL(NodoAVL nodo) {
    if (nodo == null) return;

    Vehiculo v = nodo.vehiculo;
    v.setPlaca(CifradoCesar.descifrar(v.getPlaca(), Config.CLAVE_CIFRADO));
    v.setDpi(CifradoCesar.descifrar(v.getDpi(), Config.CLAVE_CIFRADO));
    v.setNombre(CifradoCesar.descifrar(v.getNombre(), Config.CLAVE_CIFRADO));

    descifrarAVL(nodo.izquierdo);
    descifrarAVL(nodo.derecho);
}

private void descifrarABB(NodoABB nodo) {
    if (nodo == null) return;

    Vehiculo v = nodo.vehiculo;
    v.setPlaca(CifradoCesar.descifrar(v.getPlaca(), Config.CLAVE_CIFRADO));
    v.setDpi(CifradoCesar.descifrar(v.getDpi(), Config.CLAVE_CIFRADO));
    v.setNombre(CifradoCesar.descifrar(v.getNombre(), Config.CLAVE_CIFRADO));

    descifrarABB(nodo.izquierdo);
    descifrarABB(nodo.derecho);
}






private void cifrarAVL(NodoAVL nodo) {
    if (nodo == null) return;

    Vehiculo v = nodo.vehiculo;
    v.setPlaca(CifradoCesar.cifrar(v.getPlaca(), Config.CLAVE_CIFRADO));
    v.setDpi(CifradoCesar.cifrar(v.getDpi(), Config.CLAVE_CIFRADO));
    v.setNombre(CifradoCesar.cifrar(v.getNombre(), Config.CLAVE_CIFRADO));

    cifrarAVL(nodo.izquierdo);
    cifrarAVL(nodo.derecho);
}

private void cifrarABB(NodoABB nodo) {
    if (nodo == null) return;

    Vehiculo v = nodo.vehiculo;
    v.setPlaca(CifradoCesar.cifrar(v.getPlaca(), Config.CLAVE_CIFRADO));
    v.setDpi(CifradoCesar.cifrar(v.getDpi(), Config.CLAVE_CIFRADO));
    v.setNombre(CifradoCesar.cifrar(v.getNombre(), Config.CLAVE_CIFRADO));

    cifrarABB(nodo.izquierdo);
    cifrarABB(nodo.derecho);
}


    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        Desifrar_ = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();
        jButton12 = new javax.swing.JButton();
        jButton13 = new javax.swing.JButton();
        grampiz = new javax.swing.JButton();
        jButton14 = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        jButton15 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jButton16 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Dpartamento", "Placa", "Dpi", "Nombre", "Marca", "Modelo", "anio", "Multas", "Traspaso"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 10, 940, 200));

        jButton1.setText("Multas");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1110, 60, -1, -1));

        jButton2.setText("Traspaso");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1010, 60, -1, -1));

        jButton3.setText("in");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 220, -1, -1));

        jButton4.setText("pos");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 220, -1, -1));

        jButton5.setText("pre");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 220, -1, -1));

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Departamento", "Placa", "Dpi", "Nombre", "Marca", "Modelo", "anio", "Multas", "Traspaso"
            }
        ));
        jScrollPane2.setViewportView(jTable2);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 280, 940, 200));

        jLabel1.setText("avl");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1010, 40, 90, -1));

        jButton6.setText("in");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 480, -1, -1));

        jButton7.setText("pos");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 480, -1, -1));

        jButton8.setText("pre");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton8, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 480, -1, -1));

        jButton9.setText("Agregar vehiculo");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton9, new org.netbeans.lib.awtextra.AbsoluteConstraints(1020, 150, -1, -1));

        jButton10.setText("pagar");
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton10, new org.netbeans.lib.awtextra.AbsoluteConstraints(1020, 190, -1, -1));

        Desifrar_.setText("desifrar");
        Desifrar_.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Desifrar_ActionPerformed(evt);
            }
        });
        jPanel1.add(Desifrar_, new org.netbeans.lib.awtextra.AbsoluteConstraints(1020, 100, -1, -1));

        jButton11.setText("sifrar");
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton11, new org.netbeans.lib.awtextra.AbsoluteConstraints(1100, 100, -1, -1));

        jButton12.setText("Guardar");
        jButton12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton12ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton12, new org.netbeans.lib.awtextra.AbsoluteConstraints(1120, 190, -1, -1));

        jButton13.setText("Estadistica");
        jButton13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton13ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton13, new org.netbeans.lib.awtextra.AbsoluteConstraints(1150, 150, -1, -1));

        grampiz.setText("ver arbol avl");
        grampiz.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                grampizActionPerformed(evt);
            }
        });
        jPanel1.add(grampiz, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 220, -1, -1));

        jButton14.setText("ver arbol abb");
        jButton14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton14ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton14, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 480, -1, -1));
        jPanel1.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1080, 340, 150, -1));

        jButton15.setText("Buscar abb");
        jButton15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton15ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton15, new org.netbeans.lib.awtextra.AbsoluteConstraints(990, 340, -1, -1));
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 240, 300, 30));
        jPanel1.add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1090, 380, 140, -1));

        jButton16.setText("Buscaravl");
        jButton16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton16ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton16, new org.netbeans.lib.awtextra.AbsoluteConstraints(1000, 380, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1251, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        jTable1.setModel(ControladorSistema.arbolVehiculos.recorrerInOrden());
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        jTable1.setModel(ControladorSistema.arbolVehiculos.recorrerPostOrden());
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        jTable1.setModel(ControladorSistema.arbolVehiculos.recorrerPreOrden());
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        VentanaMultas ventanaMultas = new VentanaMultas(this); // pasamos la ventana principal
        ventanaMultas.setVisible(true);
        this.setVisible(false); 
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        VentanaTraspaso VentanaTraspaso = new VentanaTraspaso(this); // pasamos la ventana principal
        VentanaTraspaso.setVisible(true);
        this.setVisible(false); 
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
         jTable2.setModel(ControladorSistema.arbolesbb.recorrerInOrden());
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        jTable2.setModel(ControladorSistema.arbolesbb.recorrerPostOrden());
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        jTable2.setModel(ControladorSistema.arbolesbb.recorrerPreOrden());
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
         Pantallaagregarvehiculos VentanaTraspaso = new Pantallaagregarvehiculos(this); // pasamos la ventana principal
        VentanaTraspaso.setVisible(true);
        this.setVisible(false); 

    }//GEN-LAST:event_jButton9ActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
        VentanaHistorialVehiculo VentanaTraspaso = new VentanaHistorialVehiculo(this); // pasamos la ventana principal
        VentanaTraspaso.setVisible(true);
        this.setVisible(false); 
    }//GEN-LAST:event_jButton10ActionPerformed

    private void Desifrar_ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Desifrar_ActionPerformed
         descifrarAVL(ControladorSistema.arbolVehiculos.getRaiz());
        descifrarABB(ControladorSistema.arbolesbb.getRaiz());
        

    actualizarTablaVehiculos();
    actualizarTablaVehiculosbb();
    
    }//GEN-LAST:event_Desifrar_ActionPerformed

    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed

    
    cifrarAVL(ControladorSistema.arbolVehiculos.getRaiz());
         cifrarABB(ControladorSistema.arbolesbb.getRaiz());
         
       //  ControladorSistema.arbolVehiculos.guardarVehiculosEnArchivos("C:\\Users\\Ixtamer\\Desktop\\archivo proyecto");
        //    ControladorSistema.arbolesbb.guardarVehiculosEnArchivos("C:\\Users\\Ixtamer\\Desktop\\archivo proyecto");
   

    actualizarTablaVehiculos();
    actualizarTablaVehiculosbb();
    }//GEN-LAST:event_jButton11ActionPerformed

    private void jButton12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton12ActionPerformed
         ControladorSistema.arbolVehiculos.guardarVehiculosEnArchivos("C:\\Users\\Ixtamer\\Desktop\\archivo proyecto");
    }//GEN-LAST:event_jButton12ActionPerformed

    private void jButton13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton13ActionPerformed
        Estadistica VentanaTraspaso = new Estadistica(); // pasamos la ventana principal
        VentanaTraspaso.setVisible(true);
        this.setVisible(false); 
    }//GEN-LAST:event_jButton13ActionPerformed

    
    private void grampizActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_grampizActionPerformed
        ControladorSistema.arbolVehiculos.mostrarGraficaAVL();
    }//GEN-LAST:event_grampizActionPerformed

    private void jButton14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton14ActionPerformed
        ControladorSistema.arbolesbb.mostrarGraficaABB();
    }//GEN-LAST:event_jButton14ActionPerformed

    private void jButton15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton15ActionPerformed
        String placa = jTextField1.getText().trim();

        if (placa.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Ingrese una placa.");
            return;
        }

        long inicio = System.nanoTime(); // Tiempo inicial
        NodoABB nodo = ControladorSistema.arbolesbb.buscar(placa);
        long fin = System.nanoTime();   // Tiempo final

        long tiempo = fin - inicio;
        jLabel2.setText("Tiempo de búsqueda: " + tiempo + " ns");

        if (nodo != null) {
            // Mostrar datos si se encuentra
            Vehiculo v = nodo.vehiculo;
            JOptionPane.showMessageDialog(this, "Vehículo encontrado: " + v.getNombre());
        } else {
            JOptionPane.showMessageDialog(this, "Vehículo no encontrado.");
        }

    }//GEN-LAST:event_jButton15ActionPerformed

    private void jButton16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton16ActionPerformed
        String placa = jTextField1.getText().trim();

if (placa.isEmpty()) {
    JOptionPane.showMessageDialog(this, "Ingrese una placa.");
    return;
}

NodoAVL nodo = ControladorSistema.arbolVehiculos.buscarConTiempo(placa, jLabel2);// Se pasa el JLabel aquí

if (nodo != null) {
    Vehiculo v = nodo.vehiculo;
    JOptionPane.showMessageDialog(this, "Vehículo encontrado: " + v.getNombre());
} else {
    JOptionPane.showMessageDialog(this, "Vehículo no encontrado.");
}

    }//GEN-LAST:event_jButton16ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Desifrar_;
    private javax.swing.JButton grampiz;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton14;
    private javax.swing.JButton jButton15;
    private javax.swing.JButton jButton16;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    // End of variables declaration//GEN-END:variables
}
