
import javax.swing.JOptionPane;


public class VentanaMultas extends javax.swing.JFrame {
 private VentanaPrincipal ventanaPrincipal;
 
 
 
 
    public VentanaMultas(VentanaPrincipal vp) {
        initComponents();
        
        
        this.ventanaPrincipal = vp;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        descripcion = new javax.swing.JTextField();
        departamento = new javax.swing.JTextField();
        placa = new javax.swing.JTextField();
        fecha = new javax.swing.JTextField();
        monto = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        realizar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel1.add(descripcion, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 270, 340, -1));
        jPanel1.add(departamento, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 100, 340, -1));
        jPanel1.add(placa, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 150, 340, -1));
        jPanel1.add(fecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 210, 340, -1));
        jPanel1.add(monto, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 320, 330, -1));

        jLabel1.setText("Monto");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 330, 120, -1));

        jLabel2.setText("Departamento");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 110, 120, -1));

        jLabel3.setText("Placa");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 150, 120, -1));

        jLabel4.setText("Fecha");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 210, 120, -1));

        jLabel5.setText("Descripcion");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 280, 120, -1));

        jButton1.setText("atras");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 410, -1, -1));

        realizar.setText("realizar");
        realizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                realizarActionPerformed(evt);
            }
        });
        jPanel1.add(realizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 400, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 874, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 484, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       
        VentanaPrincipal si = new VentanaPrincipal();
        si.setVisible(true);
        this.dispose();        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void realizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_realizarActionPerformed
       String dep = departamento.getText().trim();
String plc = placa.getText().trim();
String fch = fecha.getText().trim();
String desc = descripcion.getText().trim();
double mnt = Double.parseDouble(monto.getText().trim());

NodoAVL nodoAVL = ControladorSistema.arbolVehiculos.buscar(plc);
NodoABB nodoABB = ControladorSistema.arbolesbb.buscar(plc);

if (nodoAVL != null && nodoAVL.vehiculo != null) {
    Vehiculo vehiculoAVL = nodoAVL.vehiculo;

    // Agregar multa en AVL
    vehiculoAVL.getListaMultas().agregarMulta(dep, plc, fch, desc, mnt);
    vehiculoAVL.setMultas(vehiculoAVL.getMultas() + 1);

    // Si también está en ABB, reflejar los mismos cambios
    if (nodoABB != null && nodoABB.vehiculo != null) {
        Vehiculo vehiculoABB = nodoABB.vehiculo;
        vehiculoABB.setMultas(vehiculoAVL.getMultas());

        // Copiar la lista de multas actualizada
        vehiculoABB.setListaMultas(vehiculoAVL.getListaMultas());
    }

    // Guardar los cambios
    vehiculoAVL.getListaMultas().guardarMultasEnArchivosExistentes("C:\\Users\\Ixtamer\\Desktop\\archivo proyecto");
    ControladorSistema.arbolVehiculos.guardarVehiculosEnArchivos("C:\\Users\\Ixtamer\\Desktop\\archivo proyecto");

    ventanaPrincipal.actualizarTablaVehiculos();
    ventanaPrincipal.actualizarTablaVehiculosbb();
    ventanaPrincipal.setVisible(true);
    this.dispose();

} else {
    JOptionPane.showMessageDialog(this, "Vehículo no encontrado.");
}

    




    }//GEN-LAST:event_realizarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaMultas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaMultas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaMultas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaMultas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                VentanaPrincipal vp = new VentanaPrincipal();  // crear instancia de principal
            new VentanaMultas(vp).setVisible(true);  
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField departamento;
    private javax.swing.JTextField descripcion;
    private javax.swing.JTextField fecha;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField monto;
    private javax.swing.JTextField placa;
    private javax.swing.JButton realizar;
    // End of variables declaration//GEN-END:variables
}
