import javax.swing.*;
import javax.swing.table.DefaultTableModel;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Ixtamer
 */
public class VentanaHistorialVehiculo extends javax.swing.JFrame {

    
    private VentanaPrincipal ventanaPrincipal;
    
    
    public VentanaHistorialVehiculo(VentanaPrincipal vp) {
        initComponents();
         this.ventanaPrincipal = vp;
          
    }

    
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        traspaso1 = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        mul = new javax.swing.JTable();
        platxt = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        pagar_multa__ = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 48)); // NOI18N
        jLabel1.setText("Multas");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 10, -1, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 48)); // NOI18N
        jLabel2.setText("Traspaso");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 250, -1, -1));

        traspaso1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Departamento", "Placa", "Dpi Anterior", "Nombre Anterior", "Fecha", "Dpi nuevo", "nombre nuevi"
            }
        ));
        jScrollPane1.setViewportView(traspaso1);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 330, 730, 140));

        mul.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Departamento", "Placa", "fehca", "Descripcion ", "Monto"
            }
        ));
        jScrollPane2.setViewportView(mul);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(66, 100, 730, 150));
        jPanel1.add(platxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 30, 210, -1));

        jButton1.setText("Buscar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 20, -1, -1));

        pagar_multa__.setText("Pagar");
        pagar_multa__.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pagar_multa__ActionPerformed(evt);
            }
        });
        jPanel1.add(pagar_multa__, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 120, -1, -1));

        jButton3.setText("atras");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 420, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1083, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String placa = platxt.getText().trim();
        NodoAVL nodo = ControladorSistema.arbolVehiculos.buscar(placa);

if (nodo != null && nodo.vehiculo != null) {
    Vehiculo v = nodo.vehiculo;

    String ruta = "C:\\Users\\Ixtamer\\Desktop\\archivo proyecto";
    

    // ---------- MULTAS ----------
    ControladorSistema.multas.cabeza = null;
    ControladorSistema.multas.cola = null;
    ControladorSistema.multas.cargarMultasDesdeCarpetas(ruta);

    DefaultTableModel modeloMultas = (DefaultTableModel) mul.getModel();
    modeloMultas.setRowCount(0);

    NodoMulta multaActual = ControladorSistema.multas.cabeza;
    while (multaActual != null) {
        if (multaActual.getPlaca().equalsIgnoreCase(placa)) {
            modeloMultas.addRow(new Object[]{
                multaActual.getDepartamento(),
                multaActual.getPlaca(),
                multaActual.getFecha(),
                multaActual.getDescripcion(),
                multaActual.getMonto()
            });
        }
        multaActual = multaActual.siguiente;
    }

    // ---------- TRASPASOS ----------
    ControladorSistema.traspasos.inicio = null; // ← limpia la lista circular si la manejas así
    ControladorSistema.traspasos.cargarTraspasosDesdeCarpetas(ruta);

    DefaultTableModel modeloTraspasos = (DefaultTableModel) traspaso1.getModel();
    modeloTraspasos.setRowCount(0);

    NodoTraspaso traspasoActual = ControladorSistema.traspasos.inicio;
    if (traspasoActual != null) {
        NodoTraspaso inicio = traspasoActual;
        do {
            if (traspasoActual.getPlaca().equalsIgnoreCase(placa)) {
                modeloTraspasos.addRow(new Object[]{
                    traspasoActual.getDepartamento(),
                    traspasoActual.getPlaca(),
                    traspasoActual.getDpiAnterior(),
                    traspasoActual.getNombreAnterior(),
                    traspasoActual.getFecha(),
                    traspasoActual.getDpiNuevo(),
                    traspasoActual.getNombreNuevo()
                });
            }
            traspasoActual = traspasoActual.siguiente;
        } while (traspasoActual != null && traspasoActual != inicio);
    }

} else {
    JOptionPane.showMessageDialog(this, "Vehículo no encontrado.");
}


           

    }//GEN-LAST:event_jButton1ActionPerformed

    private void pagar_multa__ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pagar_multa__ActionPerformed
                int filaSeleccionada = mul.getSelectedRow();
                    if (filaSeleccionada == -1) {
                        JOptionPane.showMessageDialog(this, "Seleccione una multa para pagar.");
                        return;
                    }

                    String ruta = "C:\\Users\\Ixtamer\\Desktop\\archivo proyecto";
                    String placa = platxt.getText().trim();
                    String fecha = (String) mul.getValueAt(filaSeleccionada, 2);

                    // Buscar la multa en la lista global
                    NodoMulta actual = ControladorSistema.multas.cabeza;
                    boolean encontrada = false;

                    while (actual != null) {
                        if (actual.getFecha().equals(fecha) && actual.getPlaca().equalsIgnoreCase(placa)) {
                            // Eliminar de la lista global
                            ControladorSistema.multas.eliminarMultaDeArchivo(ruta, actual);

                            // AVL
                            NodoAVL nodoAVL = ControladorSistema.arbolVehiculos.buscar(placa);
                            if (nodoAVL != null && nodoAVL.vehiculo != null) {
                                nodoAVL.vehiculo.getListaMultas().eliminarMultaDeArchivo(ruta, actual);
                                nodoAVL.vehiculo.restarMulta();
                                ControladorSistema.arbolVehiculos.guardarVehiculosEnArchivos(ruta);
                            }

                            // ABB
                            NodoABB nodoABB = ControladorSistema.arbolesbb.buscar(placa);
                            if (nodoABB != null && nodoABB.vehiculo != null) {
                                nodoABB.vehiculo.getListaMultas().eliminarMultaDeArchivo(ruta, actual);
                                nodoABB.vehiculo.restarMulta();
                                ControladorSistema.arbolesbb.guardarVehiculosEnArchivos(ruta);
                            }

                            encontrada = true;
                            break;
                        }
                        actual = actual.siguiente;
                    }

                    if (encontrada) {
                        ((DefaultTableModel) mul.getModel()).removeRow(filaSeleccionada);
                        ventanaPrincipal.actualizarTablaVehiculos();
                        ventanaPrincipal.actualizarTablaVehiculosbb();
                        JOptionPane.showMessageDialog(this, "Multa pagada correctamente.");
                    } else {
                        JOptionPane.showMessageDialog(this, "Multa no encontrada en la lista.");
                    }



    }//GEN-LAST:event_pagar_multa__ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        ventanaPrincipal.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaHistorialVehiculo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaHistorialVehiculo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaHistorialVehiculo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaHistorialVehiculo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                VentanaPrincipal principal = new VentanaPrincipal(); // o una versión simulada
            new VentanaHistorialVehiculo(principal).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable mul;
    private javax.swing.JButton pagar_multa__;
    private javax.swing.JTextField platxt;
    private javax.swing.JTable traspaso1;
    // End of variables declaration//GEN-END:variables
}
