
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Ixtamer
 */
public class VentanaTraspaso extends javax.swing.JFrame {
    private VentanaPrincipal ventanaPrincipal;

    /**
     * Creates new form VentanaTraspaso
     */
    public VentanaTraspaso(VentanaPrincipal vp) {
        initComponents();
        this.ventanaPrincipal = vp;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel1.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 260, 410, -1));
        jPanel1.add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 60, 410, -1));
        jPanel1.add(jTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 130, 410, -1));
        jPanel1.add(jTextField4, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 190, 410, -1));

        jLabel1.setText("Nuevo propietario");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 260, -1, -1));

        jLabel2.setText("Placa");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 70, -1, -1));

        jLabel3.setText("Fecha");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 130, -1, -1));

        jLabel4.setText("Dpi");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 200, -1, -1));

        jButton1.setText("realizar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 330, -1, -1));

        jButton2.setText("atras");
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 330, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1024, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 394, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String plc = jTextField2.getText().trim();
        String fch = jTextField3.getText().trim();
        String nuevoDpi = jTextField4.getText().trim();
        String nuevoNombre = jTextField1.getText().trim();
        
        if (plc.isEmpty() || fch.isEmpty() || nuevoDpi.isEmpty() || nuevoNombre.isEmpty()) {
        JOptionPane.showMessageDialog(this, "Todos los campos son obligatorios.");
        return;
    }

    // Buscar el vehículo por placa
    NodoAVL nodoAVL = ControladorSistema.arbolVehiculos.buscar(plc);
    NodoABB nodoABB = ControladorSistema.arbolesbb.buscar(plc);

    if (nodoAVL != null && nodoAVL.vehiculo != null) {
        Vehiculo vehiculoAVL = nodoAVL.vehiculo;

        // Datos del propietario anterior
        String dpiAnterior = vehiculoAVL.getDpi();
        String nombreAnterior = vehiculoAVL.getNombre();

        // Actualizar propietario en AVL
        vehiculoAVL.setDpi(nuevoDpi);
        vehiculoAVL.setNombre(nuevoNombre);

        // Agregar el traspaso en AVL
        vehiculoAVL.getListaTraspasos().agregarFinal(
            plc,
            dpiAnterior,
            nombreAnterior,
            fch,
            nuevoDpi,
            nuevoNombre,
            vehiculoAVL.getDepartamento()
        );

        // Aumentar contador de traspasos en AVL
        vehiculoAVL.setTraspasos(vehiculoAVL.getTraspasos() + 1);

        // También actualizar en ABB si existe
        if (nodoABB != null && nodoABB.vehiculo != null) {
            Vehiculo vehiculoABB = nodoABB.vehiculo;
            vehiculoABB.setDpi(nuevoDpi);
            vehiculoABB.setNombre(nuevoNombre);
            
            // Copiar correctamente el contador y lista de traspasos desde AVL a ABB
            vehiculoABB.setTraspasos(vehiculoAVL.getTraspasos());
            vehiculoABB.setListaTraspasos(vehiculoAVL.getListaTraspasos());
        }

        // Guardar en archivos
        vehiculoAVL.getListaTraspasos().guardarTraspasosPorDepartamento("C:\\Users\\Ixtamer\\Desktop\\archivo proyecto");
        ControladorSistema.arbolVehiculos.guardarVehiculosEnArchivos("C:\\Users\\Ixtamer\\Desktop\\archivo proyecto");

        // Actualizar tablas en GUI
        ventanaPrincipal.actualizarTablaVehiculos();
        ventanaPrincipal.actualizarTablaVehiculosbb();

        ventanaPrincipal.setVisible(true);
        this.dispose();

    } else {
        JOptionPane.showMessageDialog(this, "Vehículo no encontrado.");
    }



    
       



    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaTraspaso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaTraspaso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaTraspaso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaTraspaso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                VentanaPrincipal vp = new VentanaPrincipal(); 
                new VentanaTraspaso(vp).setVisible(true);
                
                
                ///  VentanaPrincipal vp = new VentanaPrincipal();  // crear instancia de principal
          ///  new VentanaMultas(vp).setVisible(true);  
            
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    // End of variables declaration//GEN-END:variables
}
